---
title: "TCGA_PaCaRUV_TumourPurity"
author:
- name: Ramyar Molania
  affiliation: Papenfuss Lab
  url: https://www.wehi.edu.au/people/tony-papenfuss
date: "15-02-2020"
output:
  rmdformats::readthedown:
    fig_width: 12
    fig_height: 5
    gallery: yes
    highlight: tango
    lightbox: yes
    self_contained: no
    thumbnails: no
    number_sections: yes
    toc_depth: 3
    use_bookdown: yes
  html_document2:
    df_print: paged
  html_document:
    toc_depth: '3'
    df_print: paged
params:
  update_date: !r paste("Last updated on:", Sys.Date() )
editor_options:
  chunk_output_type: console
---
`r params$update_date`

<style>
body {
text-align: justify}
</style>


```{r knitr_init, echo=FALSE, results="asis"}
library(knitr)
library(rmdformats)
library(DT)
library(BiocStyle)
options(max.print = "75")
opts_chunk$set(
  echo = FALSE,
  prompt = FALSE,
  comment = FALSE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(width = 65)
```

# setup path

```{r file-setUp, message=FALSE, include=FALSE, results=F}
mainDir <- getwd()
outPath <- "../output/"
figPath <- "../figure/"
dataPath <- "../data/"
scriptPath <- "../script/"
ifelse(!dir.exists(file.path(mainDir, outPath)), dir.create(file.path(mainDir, outPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, figPath)), dir.create(file.path(mainDir, figPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, dataPath)), dir.create(file.path(mainDir, dataPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, scriptPath)), dir.create(file.path(mainDir, scriptPath)), FALSE)
```




# Estimate tumour purity using singscore
Estimate tumor purity using singscore and gene signatures.

```{r estimate-tumorPurity}
har.cancer.dataSets <- readRDS(paste0(
   har.meta.data.path,
   'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
   )

n.cores <- detectCores()-1
cl <- makeCluster(n.cores, setup_strategy = 'sequential')
registerDoParallel(cl)
req.package <- c(
  'HDF5Array',
  'SummarizedExperiment',
  'singscore'
  )
foreach(i = 1:nrow(har.data.sets), .packages = req.package) %dopar% {
  ## raw counts data
  htseq.data <- readRDS(
    file = paste0(
      har.meta.data.path,
      har.cancer.dataSets$har.meta.data[i])
  )
  data.sets <- names(assays(htseq.data))
  gene.annot <- data.frame(rowData(htseq.data))
  stromal.immune <- row.names(gene.annot)[
    gene.annot$stromal == 'yes' |
      gene.annot$immnue == 'yes'
    ]
  sample.info <-  data.frame(colData(htseq.data))

  for(j in 1:3){
    # Tumour purity
    data.all <- assay(htseq.data, data.sets[j])
    data.all <- data.all[gene.annot$keep.cancer == 'yes', ]
    
    rank.data.all <-  singscore::rankGenes(data.all)
    purity.estimate.all <- singscore::simpleScore(
      rank.data.all,
      upSet = stromal.immune,
      centerScore = FALSE
    )$TotalScore
    sample.info[,paste0('purity.', data.sets[j])] <-
      round(purity.estimate.all, 3)
  }

  for(r in 1:3){
    # Tumour purity
    data.procod <- assay(htseq.data, data.sets[r])
    data.procod <- data.procod[
      gene.annot$protein.coding == 'yes'&
        gene.annot$keep.procod.cancer == 'yes', ]

    rank.data.procod <-  singscore::rankGenes(data.procod)
    purity.estimate.pro <- simpleScore(
      rank.data.procod,
      upSet = stromal.immune,
      centerScore = FALSE
    )$TotalScore
    sample.info[,paste0('purity.', data.sets[r], '_procod')] <-
      round(purity.estimate.pro, 3)
  }
  colData(htseq.data) <- DataFrame(sample.info)
  saveRDS(
    object = htseq.data,
    file  = paste0(
      har.meta.data.path,
      'TCGA_HTseq_Cancer_',
      har.data.sets$cancer[i],
      '.rds'))
}
stopCluster(cl)
```




# Assessing tumour purity

```{r}
### Assess purity estimates ######################################################################
path.harmomized.curated <- './TCGA_PanCancer_Harmonized_Curated/'
har.data.sets <- readRDS(
  file = paste0(
    path.harmomized.curated,
    'TCGA_Harmonized_files.rds'
    )
  )


pdf('r.pdf', width = 12, height = 6)
for(i in 1:nrow(har.data.sets)) {
  htseq.data <- readRDS(
    paste0(
    path.harmomized.curated,
    har.data.sets$HTseq.data[i]
    )
  )
  sample.info <- data.frame(colData(htseq.data))
  if(har.data.sets$cpe[i] == 'YES'){
    sample.info <- sample.info[c(
      'purity.HTseq_counts',
      'purity.HTseq_FPKM',
      'purity.HTseq_counts_procod',
      'purity.HTseq_FPKM_procod',
      'CPE_NatCom',
      'ESTIMATE_NatCom',
      'year_mda',
      'plate_expr.data'
    )]
    sample.info$CPE_NatCom[is.na(sample.info$CPE_NatCom)] <- 
      mean(sample.info$CPE_NatCom)
    sample.info$ESTIMATE_NatCom[is.na(sample.info$ESTIMATE_NatCom)] <- 
      mean(sample.info$ESTIMATE_NatCom)
    par(mfrow = c(2,4), mai = c(.6,.4,.4,.2))
    for(j in 5:6){
      sapply(
        1:4,
        function(x){
          plot(
            x = -(sample.info[,x]-1), 
            y = sample.info[,j],
            las = 2,
            bty = 'l',
            ylab = 'Purity(',
            xlab = colnames(sample.info)[x],
            main = har.data.sets$cancer[i]
          )
        }) 
    }
    par(mfrow = c(2,6), mai = c(.6,.4,.4,.2))
    for(j in 7:8){
      sapply(
        1:6,
        function(x){
          boxplot(
            -(sample.info[,x]-1) ~
            sample.info[,j],
            las = 2,
            outline = FALSE,
            ylab = 'Purity',
            xlab = colnames(sample.info)[x]
          )
        }) 
    }
  }
  else{
    print('no')
  }
  
}
dev.off()

```

