---
title: "TCGA_PaCaRUV_UnwantedVariation"
author:
- name: Ramyar Molania
  affiliation: Papenfuss Lab
  url: https://www.wehi.edu.au/people/tony-papenfuss
date: "15-02-2020"
output:
  rmdformats::readthedown:
    fig_width: 12
    fig_height: 5
    gallery: yes
    highlight: tango
    lightbox: yes
    self_contained: no
    thumbnails: no
    number_sections: yes
    toc_depth: 3
    use_bookdown: yes
  html_document2:
    df_print: paged
  html_document:
    toc_depth: '3'
    df_print: paged
params:
  update_date: !r paste("Last updated on:", Sys.Date() )
editor_options:
  chunk_output_type: console
---
`r params$update_date`

<style>
body {
text-align: justify}
</style>


```{r knitr_init, echo=FALSE, results="asis"}
library(knitr)
library(rmdformats)
library(DT)
library(BiocStyle)
options(max.print = "75")
opts_chunk$set(
  echo = FALSE,
  prompt = FALSE,
  comment = FALSE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(width = 65)
```

# setup path

```{r file-setUp, message=FALSE, include=FALSE, results=F}
mainDir <- getwd()
outPath <- "../output/"
figPath <- "../figure/"
dataPath <- "../data/"
scriptPath <- "../script/"
ifelse(!dir.exists(file.path(mainDir, outPath)), dir.create(file.path(mainDir, outPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, figPath)), dir.create(file.path(mainDir, figPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, dataPath)), dir.create(file.path(mainDir, dataPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, scriptPath)), dir.create(file.path(mainDir, scriptPath)), FALSE)
```


# Setup files

```{r setUp-path-files}
har.meta.data.path <- paste0(
  dataPath,
  'TCGA_PanCancer_Harmonized_MetaData/')

har.cancer.dataSets <- readRDS(paste0(
   har.meta.data.path,
   'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
   )
```


# PCA, RLE and correlation analysis

```{r}
# ncores <- detectCores()-1
# cl <- makeCluster(ncores, setup_strategy = 'sequential')
# registerDoParallel(cl)
# req.package <- c('SummarizedExperiment')
# foreach(i = 1:nrow(har.cancer.dataSets), .packages = req.package) %dopar%  {
#   htseq.data <- readRDS(paste0(
#     har.meta.data.path,
#     har.cancer.dataSets$har.meta.data.filtered[i]))
# 
#   row.names(htseq.data) <- rowData(htseq.data)$gene_name.
# 
#   keep.genes <- rowData(htseq.data)$keep.procod.cancer == 'yes'
#   htseq.data <- htseq.data[keep.genes , ]
#   htseq.data$ls <- colSums(as.matrix(assay(htseq.data, 'HTseq_counts')))
#   ### PCA
#   data.sets <- c(
#     'HTseq_counts',
#     'HTseq_FPKM',
#     'HTseq_FPKM.UQ'
#     )
#   pca <- lapply(
#     data.sets,
#     function(x){.pca(as.matrix(assay(htseq.data, x)), is.log = FALSE)})
#   names(pca) <- data.sets
#   ### RLE
#   rle <- lapply(
#     data.sets,
#     function(x){
#       rle.com(
#         data = as.matrix(assay(htseq.data, x)),
#         is.log = FALSE)
#     })
#   names(rle) <- data.sets
#   ### cor genes with ls
#   cor.ls <- lapply(
#     data.sets,
#     function(x){
#       .genes.var(
#         data = as.matrix(assay(htseq.data, x)),
#         is.log = FALSE,
#         var = htseq.data$ls)
#     })
#   names(cor.ls) <- data.sets
#   ### cor genes with median of RLE
#   cor.med <- lapply(
#     data.sets,
#     function(x){
#       .genes.var(
#         data = as.matrix(assay(htseq.data, x)),
#         is.log = FALSE,
#         var = rle[[x]]$rle.med)
#     })
#   names(cor.med) <- data.sets
#   ### cor genes with IQR of RLE
#   cor.iqr <- lapply(
#     data.sets,
#     function(x){
#       .genes.var(
#         data = as.matrix(assay(htseq.data, x)),
#         is.log = FALSE,
#         var = rle[[x]]$rle.iqr)
#     })
#   names(cor.iqr) <- data.sets
# 
#   all <- list(
#     pca = pca,
#     rle = rle,
#     cor.ls = cor.ls,
#     cor.med = cor.med,
#     cor.iqr = cor.iqr
#     )
# 
#   saveRDS(
#     object = all,
#     file = paste0(
#       har.meta.data.path,
#       'TCGA_HTseq_Cancer_Filtered_PCA_RLE_Cor_',
#       har.cancer.dataSets$cancer.types[i],
#       '.rds'
#     ))
# }
# stopCluster(cl)
# 
# files <- list.files(
#   path = har.meta.data.path,
#   'TCGA_HTseq_Cancer_Filtered_PCA_RLE_Cor_')
# 
# har.cancer.dataSets$rle.pca.corr <- files
# saveRDS(
#   object = har.cancer.dataSets,
#   file = paste0(
#     har.meta.data.path,
#    'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
#    )
```

# ANOVA analysis 


## Plates and Years

```{r }
har.cancer.dataSets <- readRDS(paste0(
   har.meta.data.path,
   'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
   )

anova.analysis <- list()
for(i in 1:nrow(har.cancer.dataSets)){
  
  data.sets <- c(
    'HTseq_counts',
    'HTseq_FPKM',
    'HTseq_FPKM.UQ'
    )

  htseq.data <- readRDS(paste0(
    har.meta.data.path,
    har.cancer.dataSets$har.meta.data.filtered[i]
  ))
  
  row.names(htseq.data) <- rowData(htseq.data)$gene_name.
  keep.genes <- rowData(htseq.data)$keep.procod.cancer == 'yes'
  htseq.data <- htseq.data[keep.genes , ]
  
  ### plate effects
  if(har.cancer.dataSets$AF.plates[i] > 1){
    ftest.plates <- lapply(
      data.sets,
      function(x){
        plate.effects <- .Ftest(
          data = as.matrix(assay(htseq.data, x)),
          is.log = FALSE,
          var = htseq.data$plate_expr.data,
          ncores = 11)
        })
    names(ftest.plates) <- data.sets
    }else{
      ftest.plates <- 'Not enough plates'
    }

  ### time effects
  if(har.cancer.dataSets$AF.years[i] > 1){
    ftest.years <- lapply(
      data.sets,
      function(x){
        year.effects <- .Ftest(
          data = as.matrix(assay(htseq.data, x)),
          is.log = FALSE,
          var = htseq.data$year_mda,
          ncores = 11)
        })
    names(ftest.years) <- data.sets 
    }else{
      ftest.years <- 'Not enough years'
    }

  ### batch IDs
  if(har.cancer.dataSets$AF.batchids[i] > 1){
    ftest.bacth.ids <- lapply(
      data.sets,
      function(x){
        year.effects <- .Ftest(
          data = as.matrix(assay(htseq.data, x)),
          is.log = FALSE,
          var = htseq.data$BatchId_mda,
          ncores = 11)
        })
    names(ftest.bacth.ids) <- data.sets
    }else{
      ftest.bacth.ids <- 'Not enough batch ids'
    }

  all.Ftest <- list(
    plates = ftest.plates,
    years = ftest.years,
    batchIds = ftest.bacth.ids
    )
  
  anova.analysis[[i]] <- all.Ftest
  message(i)
}


names(anova.analysis) <- har.cancer.dataSets$cancer.types
saveRDS(
  object = anova.analysis,
  paste0(
    har.meta.data.path, 'Ftest.plates.years.allCancers.rds'
  )
)
```

# Combing files
here, we combine pca, RLE, corr and ANOVA results.

```{r}
# har.cancer.dataSets <- readRDS(paste0(
#   har.meta.data.path, 'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
#   )
# anova.test <- readRDS(paste0(
#   har.meta.data.path, 'Ftest.plates.years.allCancers.rds')
#   )
# 
# for(i in 1:nrow(har.cancer.dataSets)){
#   pca.rle.corr <- readRDS(paste0(
#     har.meta.data.path, har.cancer.dataSets$rle.pca.corr[i]
#   ))
#   anova <- anova.test[[i]]
#   all <- append(pca.rle.corr, anova)
# 
#   saveRDS(
#     object = all,
#     file = paste0(
#       har.meta.data.path,
#       'TCGA_HTseq_Cancer_Filtered_PCA_RLE_Corr_Ftest_',
#       har.cancer.dataSets$cancer.types[i],
#       '.rds'))
# 
# }
# 
# files <- list.files(
#   path = har.meta.data.path,
#   pattern = 'TCGA_HTseq_Cancer_Filtered_PCA_RLE_Corr_Ftest_'
# )
# 
# har.cancer.dataSets$rle.pca.corr.ftest <- files
# saveRDS(
#   object = har.cancer.dataSets,
#   file = paste0(
#   har.meta.data.path, 'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
#   )
```


# EDA

```{r}
har.meta.data.path <- paste0(
  dataPath,
  'TCGA_PanCancer_Harmonized_MetaData/'
  )
data.sets <- c(
  'HTseq_counts',
  'HTseq_FPKM',
  'HTseq_FPKM.UQ'
  )
col.years <- RColorBrewer::brewer.pal(n = 8, 'Dark2')
names(col.years) <- c(
  '2008', 
  '2009', 
  '2010', 
  '2011', 
  '2012', 
  '2013', 
  '2014', 
  '2015')

col.datasets <- RColorBrewer::brewer.pal(n = 8, 'Dark2')[c(1:3)]
names(col.datasets) <- data.sets

## Files
har.cancer.dataSets <- readRDS(paste0(
  har.meta.data.path, 
  'TCGA_Harmonized_Cancer_MetaDataFiles.rds')
  )

gg.them <- theme(
  panel.background = element_blank(),
  axis.line = element_line(colour = 'black'),
  axis.title.x = element_text(size = 12),
  axis.title.y = element_text(size = 12),
  plot.title = element_text(size = 15),
  axis.text.x = element_text(size = 8),
  axis.text.y = element_text(size = 8),
  legend.text = element_text(size = 10),
  legend.title = element_text(size = 14),
  strip.text.x = element_text(size = 10)
)


ncores <- detectCores()-1
cl <- makeCluster(ncores, setup_strategy = 'sequential')
registerDoParallel(cl)
req.package <- c('SummarizedExperiment', 'ggplot2', 'ggpubr', 'cowplot', 'gridExtra', 'dplyr')

foreach(i = 1:nrow(har.cancer.dataSets), .packages = req.package) %dopar% {
  all.test <- readRDS(paste0(
    har.meta.data.path,
    har.cancer.dataSets$rle.pca.corr.ftest[i])
    )
  htseq.data <- readRDS(paste0(
    har.meta.data.path,
    har.cancer.dataSets$har.meta.data.filtered[i])
    )
  if(i == 14){
    htseq.data$year_mda <- as.factor(htseq.data$year_mda)
  }else{htseq.data = htseq.data}
  keep.genes <- rowData(htseq.data)$keep.procod.cancer == 'yes'
  raw.counts <- assay(htseq.data, 'HTseq_counts')
  ls <- log2(colSums(raw.counts[keep.genes , ]))
  
  pdf(paste0(
    figPath,
    'TCGA_PanCancer_PCA_RLE_Corr_Ftest_',
    har.cancer.dataSets$cancer.types[i],
    '.pdf'), 
    width = 12, 
    height = 4
    )
  
  ### PCA- variation
  pcs.var <- sapply(
    data.sets, 
    function(x) all.test$pca[[x]]$var)[1:20, ]
  pcs.var <- pcs.var %>% 
    data.frame(.) %>% 
    mutate(PCs = c(1:20)) %>% 
    tidyr::pivot_longer(
      -PCs,
      names_to = 'Datasets',
      values_to = 'Variation') %>% 
    data.frame(.)
  p <- ggplot(pcs.var, aes(x = PCs, y = Variation )) +
    geom_point() +
    geom_line() +
    ylab('Variation (percentage)') +
    facet_wrap(~Datasets) +
    scale_x_continuous(breaks = scales::pretty_breaks(20), limits = c(NA, NA)) +
    gg.them
  print(p)
  ### PCA
  sapply(
    data.sets, 
    function(x){
      pcs <- all.test$pca[[x]]
      p <- .scatter.density.pc(
        pcs = pcs$sing.val$u[,1:3],
        pc.var = pcs$var,
        group.name = 'Time (years)',
        group = htseq.data$year_mda,
        color = col.years)
      do.call(grid.arrange, c(p, ncol = 4, top = x))
      })
  ### PCA - library size
    lapply(
    data.sets, 
    function(x){
      pcs <- all.test$pca[[x]]
      pcs = as.data.frame(pcs$sing.val$u[,1:3])
      pcs$ls <- ls
      colnames(pcs)[1:3] <- paste0('PC', c(1:3))
      pcs <- pcs %>% 
        tidyr::pivot_longer(
          -ls,
          values_to = 'PCs',
          names_to = 'PC') %>% 
        data.frame(.)
      p <- ggplot(pcs, aes(x = PCs, y = ls)) +
        geom_point(shape = 21, fill = 'gray', color = 'gray40' , size = 1) +
        geom_density_2d(size = 0.3) +
        facet_wrap(~PC, scales = 'free_x') +
        xlab('') + ylab(expression(Lo2[2]~'library size')) +
        ggpubr::stat_cor(method = "pearson", aes(label = ..r.label..)) +
        ggtitle(x) +
        gg.them
      print(p)
      })
    ### PCA - time year
    lapply(
    data.sets, 
    function(x){
      pcs <- all.test$pca[[x]]
      pcs = as.data.frame(pcs$sing.val$u[,1:3])
      pcs$time <- htseq.data$year_mda
      colnames(pcs)[1:3] <- paste0('PC', c(1:3))
      pcs <- pcs %>% 
        tidyr::pivot_longer(
          -time,
          values_to = 'PCs',
          names_to = 'PC') %>% 
        data.frame(.)
      p <- ggplot(pcs, aes(x = time, y = PCs)) +
        geom_boxplot(outlier.shape = NA) + 
        facet_wrap(~PC, scales = 'free_y') +
        xlab('Time(years)') +
        ggtitle(x) +
        gg.them
      print(p)
      })
    ### PCA - plates
    p <- lapply(
    data.sets, 
    function(x){
      pcs <- all.test$pca[[x]]
      pcs = as.data.frame(pcs$sing.val$u[,1:3])
      pcs$plates <- htseq.data$PlateId_mda
      colnames(pcs)[1:3] <- paste0('PC', c(1:3))
      pcs <- pcs %>% 
        tidyr::pivot_longer(
          -plates,
          values_to = 'PCs',
          names_to = 'PC') %>% 
        data.frame(.)
      p <- ggplot(pcs, aes(x = plates, y = PCs)) +
        geom_boxplot(outlier.shape = NA) + 
        facet_wrap(~PC, scales = 'free_y') +
        xlab('Plates') +
        ggtitle(x) +
        gg.them
      print(p)
      })
    ### PCA - batch
    p <- lapply(
    data.sets, 
    function(x){
      pcs <- all.test$pca[[x]]
      pcs = as.data.frame(pcs$sing.val$u[,1:3])
      pcs$batchids <- htseq.data$BatchId_mda
      colnames(pcs)[1:3] <- paste0('PC', c(1:3))
      pcs <- pcs %>% 
        tidyr::pivot_longer(
          -batchids,
          values_to = 'PCs',
          names_to = 'PC') %>% 
        data.frame(.)
      p <- ggplot(pcs, aes(x = batchids, y = PCs)) +
        geom_boxplot(outlier.shape = NA) + 
        facet_wrap(~PC, scales = 'free_y') +
        xlab('Batch Ids') +
        ggtitle(x) +
        gg.them
      print(p)
      })
  ### RLE plot - medians
  rle.med <- sapply(
    data.sets, 
    function(x) all.test$rle[[x]]$rle.med
    )
  rle.med <- rle.med %>% 
    data.frame(.) %>% 
    mutate(Samples = c(1:nrow(rle.med))) %>% 
    tidyr::pivot_longer(
      -Samples,
      names_to = 'Datasets',
      values_to = 'RLE.med'
      )
  p <- ggplot(rle.med, aes(x = Samples, y = RLE.med)) +
    geom_point(shape = 21, fill = 'gray', color = 'gray40' , size = 2) + 
    facet_grid(~Datasets) + 
    geom_hline(yintercept = 0, col = 'red', lty = 2) +
    ylab('Median of RLE') + 
    scale_y_continuous(breaks = scales::pretty_breaks(7), limits = c(NA, NA)) +
    gg.them
  print(p)
  ### RLE plot - IQR
  rle.med <- sapply(
    data.sets, 
    function(x) all.test$rle[[x]]$rle.iqr
    )
  rle.med <- rle.med %>% 
    data.frame(.) %>% 
    mutate(Samples = c(1:nrow(rle.med))) %>% 
    tidyr::pivot_longer(
      -Samples,
      names_to = 'Datasets',
      values_to = 'RLE.med'
      )
  p <- ggplot(rle.med, aes(x = Samples, y = RLE.med)) +
    geom_point(shape = 21, fill = 'gray', color = 'gray40' , size = 2) + 
    facet_grid(~Datasets) + 
    ylab('IQR of RLE') + 
    scale_y_continuous(breaks = scales::pretty_breaks(7), limits = c(NA, NA)) +
    gg.them
  print(p)
  ### RLE plot - medians - time
   rle.med <- sapply(
    data.sets, 
    function(x) all.test$rle[[x]]$rle.med
    )
   rle.med <- rle.med %>% 
    data.frame(.) %>% 
    dplyr::mutate(Time = htseq.data$year_mda) %>% 
    tidyr::pivot_longer(
      -Time,
      names_to = 'Datasets',
      values_to = 'RLE.med'
      )
  p <- ggplot(rle.med, aes(x = Time, y = RLE.med)) +
    geom_boxplot(outlier.shape = NA) +
    geom_hline(yintercept = 0, col = 'red', lty = 2) +
    facet_wrap(~Datasets) +
    gg.them + 
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))
  print(p)
  ### RLE plot - medians - plates
   rle.med <- sapply(
    data.sets, 
    function(x) all.test$rle[[x]]$rle.med
    )
   rle.med <- rle.med %>% 
    data.frame(.) %>% 
    dplyr::mutate(Time = htseq.data$plate_expr.data) %>% 
    tidyr::pivot_longer(
      -Time,
      names_to = 'Datasets',
      values_to = 'RLE.med')
  p <- ggplot(rle.med, aes(x = Time, y = RLE.med)) +
    geom_boxplot(outlier.shape = NA) +
    geom_hline(yintercept = 0, col = 'red', lty = 2) +
    ylab('Plates') + xlab('Median of RLE') + 
    facet_wrap(~Datasets) +
    gg.them + 
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))
  print(p)
    ### RLE plot - medians - batch.ids
   rle.med <- sapply(
    data.sets, 
    function(x) all.test$rle[[x]]$rle.med
    )
   rle.med <- rle.med %>% 
    data.frame(.) %>% 
    dplyr::mutate(Time = htseq.data$BatchId_mda) %>% 
    tidyr::pivot_longer(
      -Time,
      names_to = 'Datasets',
      values_to = 'RLE.med')
  p <- ggplot(rle.med, aes(x = Time, y = RLE.med)) +
    geom_boxplot(outlier.shape = NA) +
    geom_hline(yintercept = 0, col = 'red', lty = 2) +
    facet_wrap(~Datasets) +
    ylab('Batch ids') + xlab('Median of RLE') + 
    gg.them + 
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))
  print(p)
  ### corr genes and ls
  corr.gene.ls <- do.call(cbind, all.test$cor.ls) %>% 
    as.data.frame(.) %>% 
    tidyr::pivot_longer(
      everything(),
      names_to = "Datasets",
      values_to = "corr.coeff") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(corr.coeff, fill = Datasets)) +
    geom_histogram(alpha = 0.5, position = "identity") +
    xlab('Spearman correlation coefficient') +
    ylab('Frequency') +
    ggtitle('Correlation between individual gene expression and library size') +
    gg.them
  print(p)
  ### corr genes and medRLE
  corr.gene.ls <- do.call(cbind, all.test$cor.med) %>% 
    as.data.frame(.) %>% 
    tidyr::pivot_longer(
      everything(),
      names_to = "dataSets",
      values_to = "corr.coeff") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(corr.coeff, fill = dataSets)) +
    geom_histogram(alpha = 0.5, position = "identity") + 
    scale_fill_manual(values = col.datasets) +
    xlab('Spearman correlation coefficient') +
    ylab('Frequency') +
    ggtitle('Correlation between individual gene expression and median of RLE') +
    gg.them
  print(p)
  ### corr genes and iqrRLE
  corr.gene.ls <- do.call(cbind, all.test$cor.iqr) %>% 
    as.data.frame(.) %>% 
    tidyr::pivot_longer(
      everything(),
      names_to = "dataSets",
      values_to = "corr.coeff") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(corr.coeff, fill = dataSets)) +
    geom_histogram(alpha = 0.8, position = "identity") +
    scale_fill_manual(values = col.datasets) +
    xlab('Spearman correlation coefficients') + 
    ylab('Frequency') +
    ggtitle('Correlation between individual genes and IQR of RLE') +
    gg.them
  print(p)
  ### corr genes.ls and gene.medRLE
  cor.ls <- do.call(cbind, all.test$cor.ls)
  cor.rle <- do.call(cbind, all.test$cor.med)
  pList <- list()
  for(j in 1:3){
    df <- data.frame(
      corr.ls = cor.ls[,j],
      corr.rle = cor.rle[,j]
    )
    p <- ggplot(df, aes(x = corr.ls,  y = corr.rle)) + 
      geom_point(alpha = 0.3, shape = 16) + 
      geom_density_2d(size = 0.3) +
      xlab('Correlation genes vs. library size') +
      ylab('Correlation genes vs. median of RLE') +
      geom_abline(intercept = 0, slope = 1, color = 'red')
    pList[[j]] <- p
  }
  do.call(grid.arrange, c(pList, ncol = 3))
  
  ### corr genes.ls and gene.iqrRLE
  cor.ls <- do.call(cbind, all.test$cor.ls)
  cor.rle <- do.call(cbind, all.test$cor.iqr)
  pList <- list()
  for(j in 1:3){
    df <- data.frame(
      corr.ls = cor.ls[,j],
      corr.rle = cor.rle[,j]
    )
    p <- ggplot(df, aes(x = corr.ls,  y = corr.rle)) + 
      geom_point(alpha = 0.3, shape = 16) + 
      geom_density_2d(size = 0.3) +
      xlab('Correlation genes vs. library size') +
      ylab('Correlation genes vs. IQR of RLE') +
      geom_abline(intercept = 0, slope = 1, color = 'red')
    pList[[j]] <- p
  }
  do.call(grid.arrange, c(pList, ncol = 3))
  
  ### Ftest plates
  if(har.cancer.dataSets$AF.plates[i] > 1){
    corr.gene.ls <- do.call(cbind, all.test$plates)  %>% 
      dplyr::select(.,ends_with('FValue')) %>% 
      dplyr::rename_all(funs(stringr::str_replace(., '.FValue', ''))) %>% 
      tidyr::pivot_longer(
      everything(),
      names_to = "Datasets",
      values_to = "Fstat") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(log2(Fstat), fill = Datasets)) +
    geom_histogram(alpha = 0.8, position = "identity") +
    scale_fill_manual(values = col.datasets) +
    xlab(expression(Log[2]~'F statitics')) + 
    ylab('Frequency') +
    ggtitle('Ftest of individual genes epxression across plates') +
    gg.them 
  print(p)
  }else(print('NA'))
  ### Ftest years
  if(har.cancer.dataSets$AF.years[i] > 1){
    corr.gene.ls <- do.call(cbind, all.test$years)  %>% 
      dplyr::select(ends_with('FValue')) %>% 
      dplyr::rename_all(funs(stringr::str_replace(., '.FValue', ''))) %>% 
      tidyr::pivot_longer(
      everything(),
      names_to = "Datasets",
      values_to = "Fstat") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(log2(Fstat), fill = Datasets)) +
    geom_histogram(alpha = 0.8, position = "identity") +
    scale_fill_manual(values = col.datasets) +
    xlab(expression(Log[2]~'F statitics')) + 
    ylab('Frequency') +
    ggtitle('Ftest of individual genes epxression across years') +
    gg.them 
  print(p)
  }else(print('NA'))
  ### Batch Ids
  if(har.cancer.dataSets$AF.batchids[i] > 1){
    corr.gene.ls <- do.call(cbind, all.test$batchIds)  %>% 
      dplyr::select(ends_with('FValue')) %>% 
      dplyr::rename_all(funs(stringr::str_replace(., '.FValue', ''))) %>% 
      tidyr::pivot_longer(
      everything(),
      names_to = "Datasets",
      values_to = "Fstat") %>% 
    data.frame()
  p <- ggplot(corr.gene.ls, aes(log2(Fstat), fill = Datasets)) +
    geom_histogram(alpha = 0.8, position = "identity") +
    xlab(expression(Log[2]~'F statitics')) + 
     scale_fill_manual(values = col.datasets) +
    ylab('Frequency') +
    ggtitle('Ftest of individual genes epxression across batch ids') +
    gg.them 
  print(p)
  }else(print('NA'))
  dev.off()
  }
stopCluster(cl)
```









